### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by yoyurec** [SimenB/stylint-stylish#1]
Can't setup stylish to work - It doesn't output errors
How to setup & configure it to work with https://github.com/danielhusar/gulp-stylint ?
tnx

**Comment by SimenB** [comment]
How do you call stylint? If using gulp, can you post the relevant code?

**Comment by yoyurec** [comment]
gulp:
```
gulp.task('stylus-lint', function () {
    return gulp
        .src('css/app.styl')
        .pipe(stylint({failOnError: true}));
});
```
task is working with default styles, but when i setup yours - it stop ((
config (.stylintrc):
```
...
    "reporter": "stylint-stylish",
...
```

**Comment by SimenB** [comment]
@yoyurec Just published `1.1.8` of `gulp-stylint`, please try again and report back.

I didn't test using this before the refactor of the gulp-plugin...

**Comment by yoyurec** [comment]
works perfect! tnx
![screenshot-github com 2015-08-03 11-39-51](https://cloud.githubusercontent.com/assets/137919/9033928/7a1cf722-39d4-11e5-8210-bfa5ab0bd70c.png)

**Comment by SimenB** [comment]
Awesome!

Currently it will print a report per file, and not a total. Currently working on that :smile:  rossPatton/stylint#161

**Comment by yoyurec** [comment]
update ))
Atom editor doesn't lint with (maybe parser can't recognize your format)
```
    "reporter": "stylint-stylish"
``` 
so i should set somehow **stylint-stylish** on gulp task\, but no luck:
```
...
        .pipe(stylint({reporter: 'stylint-stylish'}));
...
```
with quotes:
```
...
        .pipe(stylint({'reporter': 'stylint-stylish'}));
...
```

**Comment by SimenB** [comment]
Probably related to danielhusar/gulp-stylint#13, I'll try to fix it there

**Comment by SimenB** [comment]
@yoyurec Was it fixed with latest `gulp-stylint`?

**Comment by yoyurec** [comment]
lools like no (((
maybe i'm using it wrong.
https://github.com/danielhusar/gulp-stylint/issues/13#issuecomment-127623987

**Comment by Arcanemagus** [comment]
By the way, the reason it isn't working when this is specified is that the output is being parsed manually, and this changed the output. I'm looking into forcing a reporter in https://github.com/AtomLinter/linter-stylint/issues/65, but running into issues with all the current ones 😛.

**Comment by SimenB** [comment]
@Arcanemagus What sort of issue?

**Comment by Arcanemagus** [comment]
https://github.com/SimenB/stylint-stylish/issues/52 would make this usable, `stylint-json-reporter` is unusable due to https://github.com/sertae/stylint-json-reporter/issues/1.

**Comment by SimenB** [comment]
Submitted sertae/stylint-json-reporter#2, seems much better for you to read the object than trying to parse the string I output...

**Comment by Arcanemagus** [comment]
Most definitely, I just didn't have the time to dig into the `stylint` + `stylint-json-reporter` source code to figure out what is broken, thanks!
