### ISSUE TITLE
Icons are showing up as squares in command line output

### ISSUE THREAD

**Issue by Sawtaytoes** [SimenB/stylint-stylish#100]
For some reason, the icons are showing up as squares in command line output when using Cmder or Windows cmd.

![image](https://user-images.githubusercontent.com/3948069/37737283-466862b6-2d21-11e8-948a-1064f382a274.png)

I'm using Windows 10 64-bit and the Consolas font on this particular machine. I also tried Operator Mono and Input Mono fonts. What should I be using instead?

**Comment by SimenB** [comment]
The symbols comes from https://github.com/sindresorhus/log-symbols, mind raising an issue there?

**Comment by Sawtaytoes** [comment]
https://github.com/sindresorhus/log-symbols/issues/17

**Comment by SimenB** [comment]
Happy to reopen if it's actually an issue in this repo
