### ISSUE TITLE
Use actual "Stylish" formatting.

### ISSUE THREAD

**Issue by joezimjs** [SimenB/stylint-stylish#2]
stylint-stylish indents the singular warnings/errors REALLY far. Why? 

**Compare**

stylint-stylish
<img width="585" alt="stylint" src="https://cloud.githubusercontent.com/assets/1313898/9052612/4bde1f3e-3a2f-11e5-873d-a22e4e1629de.png">

jshint-stylish
![jshint](https://cloud.githubusercontent.com/assets/1313898/9052620/5734e91c-3a2f-11e5-89fa-1057c432e944.png)

eslint-stylish
![eslint](https://cloud.githubusercontent.com/assets/1313898/9052626/5e27ab06-3a2f-11e5-9d70-7127c9e94535.png)

If you are going to use the "Stylish" nomenclature, you should probably more closely adhere to the formatting that "Stylish" formatters are known for. Other than the ridiculous indentation and the lack of column number, you did a decent job, but that indentation is making so many errors flow to a new line.

**Comment by SimenB** [comment]
Stylint doesn't report column  numbers, so that part I can't do anything with.
The indentation though should be fixable :smile:

**Comment by SimenB** [comment]
@joezimjs Better?

![image](https://cloud.githubusercontent.com/assets/1404810/9054412/537ed150-3a81-11e5-99ba-7135203bcb90.png)

**Comment by joezimjs** [comment]
I'm not particularly worried about column numbers, so whatever. That looks much better though.
