### ISSUE TITLE
UNMET PEER DEPENDENCY styling@1.x while trying to install package as global

### ISSUE THREAD

**Issue by Kamilius** [SimenB/stylint-stylish#28]
![screen shot 2016-05-27 at 11 02 18 am](https://cloud.githubusercontent.com/assets/3115794/15601858/828bbed2-23fa-11e6-9d3a-b802b22321a2.png)

I'm getting this message, when trying to globally install `stylint-stylish`. And the thing is, that I've successfully installed `stylint@1.3.10` prior to that.

![screen shot 2016-05-27 at 11 03 31 am](https://cloud.githubusercontent.com/assets/3115794/15601893/bc34c778-23fa-11e6-8dc3-f9647451f8f1.png)

Any clues on how to fix this?
Thanks.

**Comment by SimenB** [comment]
Hmm, I haven't tried it globally before...

Solution seems to be to install both at the same time : https://github.com/yeoman/generator-angular/issues/1192#issuecomment-151727263

No idea why... That works for me at my machine at least!

**Comment by SimenB** [comment]
@Kamilius can I close, or do you face issues using the module globally?

**Comment by Kamilius** [comment]
I believe this one can be closed, as problem disappeared after both packages reinstallation

**Comment by SimenB** [comment]
In case people find this: seems to be reported to npm as well. 

npm/npm#12905
