### ISSUE TITLE
Option to show the rule name

### ISSUE THREAD

**Issue by Arcanemagus** [SimenB/stylint-stylish#52]
It seems like there is no way currently to display the name of the rule that is triggering the message, could a reporter option enabling that be added?

**Comment by SimenB** [comment]
I can add it. It's in ESlint's output by deafult

**Comment by SimenB** [comment]
Stylint doesn't report this... Blocked by rossPatton/stylint#345

**Comment by Arcanemagus** [comment]
Interesting, it's showing in the default output:
![image](https://cloud.githubusercontent.com/assets/427137/18970470/45307ac4-8646-11e6-90a9-72e72a28a9b4.png)

**Comment by SimenB** [comment]
I didn't see it in the default cache, so I just assumed it wasn't there...

#53
